name: e2e

on:
  # pull_request:
  workflow_dispatch: # TODO: fix e2e

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run db & api with docker compose
        run: docker compose up -d

      - name: wait until ready
        run: until [ $(docker compose ps | grep -c healthy) -eq 2 ]; do docker compose ps; sleep 1;  done

      - name: test hello world
        run: |
          curl -s localhost:8000 | jq -r .message
          test "$(curl -s localhost:8000 | jq -r .message)" = "Hello World"

      - name: test len(users) == 0
        run: |
          test $(curl -s -X 'GET' \
            'http://localhost:8000/users/?skip=0&limit=100' \
            -H 'accept: application/json' | jq length) = 0

      - name: create a user
        run: |
          curl -s -X 'POST' \
            'http://localhost:8000/users/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{
              "email": "string",
              "password": "string"
            }'

      - name: test len(users) == 1
        run: |
          test $(curl -s -X 'GET' \
            'http://localhost:8000/users/?skip=0&limit=100' \
            -H 'accept: application/json' | jq length) = 1
